### PR TITLE
Better recognition of touch controllers & quest models

### PR DESCRIPTION
**Pull request by lvoogdt**
The quest models only show up when the running app/game hasnt replaced it with its own controllers (where the angle is off).

@btw all the buttons seem to work, but the trigger button does not work somehow.

### CODE REVIEW

**Comment by lvoogdt** [comment]
I got these names for controllerTrackingSystemName etc. by looking at the names reported by openvr when connecting my Oculus Rift CV1 and touch controllers

**Comment by FricoRico** [comment]
Maybe add `.obj` and `.mtl` files to GIT LFS?

**Comment by Irastris** [comment]
Uploaded a version of my Quest rendermodel that doesn't follow the CV1 naming scheme to avoid confusion here: https://files.catbox.moe/1zbqvu.zip

Can your pull request be updated to reflect this?

**Comment by lvoogdt** [comment]
See #315

**Pull request closed without merging**
